name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build Gouraud-Phong:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up build
      run: sudo sh ./scripts/build_setup.sh
    - name: Compile
      run: make shader=gouraud reflection=phong
    - name: Run Tests
      run: ./out/renderer test
  Build Gouraud-Blinn:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up build
      run: sudo sh ./scripts/build_setup.sh
    - name: Compile
      run: make shader=gouraud reflection=blinn
    - name: Run Tests
      run: ./out/renderer test
  Build Phong-Phong:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up build
      run: sudo sh ./scripts/build_setup.sh
    - name: Compile
      run: make shader=phong reflection=phong
    - name: Run Tests
      run: ./out/renderer test
  Build Phong-Blinn:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up build
      run: sudo sh ./scripts/build_setup.sh
    - name: Compile
      run: make shader=phong reflection=blinn
    - name: Run Tests
      run: ./out/renderer test
  Build PBR:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up build
      run: sudo sh ./scripts/build_setup.sh
    - name: Compile
      run: make shader=pbr
    - name: Run Tests
      run: ./out/renderer test
