name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run as Admin
      run: sudo su
    - name: Build
      run: ./build.sh
    - name: Run Tests
      run: ./out/renderer test
