name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: sudo sh ./scripts/build.sh
    - name: Run Tests
      run: ./out/renderer test
