name: Build + Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create dir
      run: mkdir ./out
    - name: make
      run: make
    - name: test
      run: ./out/renderer test
